// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';
import 'package:login_google_application/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQt1lpHoGt2bw9wzksUysok1p1F64se88',
    appId: '1:950699431094:web:7f4645f99c3abd4d4e4217',
    messagingSenderId: '950699431094',
    projectId: 'flutter-auth-ca11b',
    authDomain: 'flutter-auth-ca11b.firebaseapp.com',
    storageBucket: 'flutter-auth-ca11b.firebasestorage.app',
    measurementId: 'G-JQRBN90P41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq9Hc1fltNW1JNtLyCUg2AHXVAK7-dArY',
    appId: '1:950699431094:android:87efec788adbf6a94e4217',
    messagingSenderId: '950699431094',
    projectId: 'flutter-auth-ca11b',
    storageBucket: 'flutter-auth-ca11b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUf0Ni7eEF_08G1HmVjTGG_y4ZUAALluM',
    appId: '1:950699431094:ios:192f8e0b8fcd1a9e4e4217',
    messagingSenderId: '950699431094',
    projectId: 'flutter-auth-ca11b',
    storageBucket: 'flutter-auth-ca11b.firebasestorage.app',
    iosClientId: '950699431094-b01m80dkhs7uvdagrbossecehs8hr1r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGoogleApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUf0Ni7eEF_08G1HmVjTGG_y4ZUAALluM',
    appId: '1:950699431094:ios:192f8e0b8fcd1a9e4e4217',
    messagingSenderId: '950699431094',
    projectId: 'flutter-auth-ca11b',
    storageBucket: 'flutter-auth-ca11b.firebasestorage.app',
    iosClientId: '950699431094-b01m80dkhs7uvdagrbossecehs8hr1r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGoogleApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQt1lpHoGt2bw9wzksUysok1p1F64se88',
    appId: '1:950699431094:web:085901eee902e3054e4217',
    messagingSenderId: '950699431094',
    projectId: 'flutter-auth-ca11b',
    authDomain: 'flutter-auth-ca11b.firebaseapp.com',
    storageBucket: 'flutter-auth-ca11b.firebasestorage.app',
    measurementId: 'G-HYC91BB28X',
  );
}
